#!/bin/bash
export TERM=xterm

# If id command returns zero, you have root access.
if [ $(id -u) -eq 0 ];
then # you are root, set red colour prompt
  PS1="\\[$(tput setaf 1)\\]\\u@\\h:\\w #\\[$(tput sgr0)\\] "
  export PATH=/usr/sbin:/sbin:$PATH
else # normal
  PS1="\[$(tput setaf 2)\]\\u@\\h:\\w $ \[$(tput sgr0)\] "
fi
