#!/bin/bash
HOST=http://www.nooplinux.org/noop
PKGHOST=$HOST/packages/`uname -m`

#Check for stuff
if [ -e /usr/bin/which ];
then
	WHICH=/usr/bin/which
else
	if [ -e /bin/which ];
	then
		WHICH=/bin/which
	else
		echo '"which" not found in /usr/bin or /bin, please install which to continue';
		exit 1
	fi
fi

PROGS=('wget' 'tar' 'uname' 'chmod' 'mount' 'chroot' 'rm' 'ln' 'curl')
for i in ${PROGS[@]};
do
	if [ `$WHICH $i | wc -l` == "0" ];
	then
		echo "$i not found, please install to continue";
		exit 1
	fi
done

WGET=`$WHICH wget`
TAR=`$WHICH tar`
UNAME=`$WHICH uname`
CHMOD=`$WHICH chmod`
MOUNT=`$WHICH mount`
CHROOT=`$WHICH chroot`
RM=`$WHICH rm`
LN=`$WHICH ln`
CURL=`$WHICH curl`

if [ -z $1 ]; then
	echo instlr PREFIX
	exit 0
fi

PREFIX=$1

cd $PREFIX
$WGET $PKGHOST/file-base.tar.bz2 -O$PREFIX/file-base.tar.bz2
$TAR xf file-base.tar.bz2
$RM file-base.tar.bz2

if [ `$UNAME -m` == "x86_64" ]; then
	$LN -s lib lib64
	cd usr
	$LN -s lib lib64
fi


$CURL -L -s https://github.com/nemasu/noop-linux/raw/master/pkgr > $PREFIX/usr/sbin/pkgr

$CHMOD a+x $PREFIX/usr/sbin/pkgr
export PATH=$PREFIX/usr/sbin:$PATH

PREFIX=$PREFIX pkgr -s
export PKGR_SUPPRESS_P_OUTPUT=1

if [ "`$UNAME -m`" != "armv6l" ];
then
	EXTRA=grub
fi

for i in glibc trunc which busybox bc tzdata systemd shadow coreutils bash wget grep sed perl findutils curl gawk procps tar bzip2 gzip dhcpcd inetutils iproute2 wpa_supplicant wireless_tools kbd vim ca-certificates openresolv networkmanager linux-kernel linux-firmware $EXTRA;
do
	PREFIX=$PREFIX pkgr -i $i
done

$MOUNT --bind /dev $PREFIX/dev
$MOUNT --bind /sys $PREFIX/sys
$CHROOT $PREFIX ldconfig
$CHROOT $PREFIX /bin/bash --login pkgr -init
