#!/bin/bash
HOST=http://www.nooplinux.org/noop
PKGHOST=$HOST/packages/`uname -m`

#Check for stuff
if [ -e /usr/bin/which ];
then
	WHICH=/usr/bin/which
else
	if [ -e /bin/which ];
	then
		WHICH=/bin/which
	else
		echo '"which" not found in /usr/bin or /bin, please install which to continue';
		exit 1
	fi
fi

PROGS=('wget' 'tar' 'uname' 'chmod' 'mount' 'chroot' 'rm' 'ln' 'curl')
for i in ${PROGS[@]};
do
	if [ `$WHICH $i | wc -l` == "0" ];
	then
		echo "$i not found, please install to continue";
		exit 1
	fi
done

WGET=`$WHICH wget`
TAR=`$WHICH tar`
UNAME=`$WHICH uname`
CHMOD=`$WHICH chmod`
MOUNT=`$WHICH mount`
CHROOT=`$WHICH chroot`
RM=`$WHICH rm`
LN=`$WHICH ln`
CURL=`$WHICH curl`

if [ -z $1 ]; then
	echo instlr PREFIX
	exit 0
fi

PREFIX=$1

if [ ! -d "$PREFIX" ]; then
	
	if [ "$LANG" == "ja_JP.UTF-8" ]; then
		echo "エラー：有効なディレクトリを提供してください。";
	else
		echo "Error: Please provide a valid directory";
	fi
	
	exit 1;
fi

if [ -z "$NOOP_ISO_CREATE" ];
then
	if [ "$LANG" == "ja_JP.UTF-8" ]; then
		echo "インタネットやメディアからインストールしますか？ (internet/media)：";
	else
		echo "Get packages from the internet, or use booted media? (internet/media): "; 
	fi
	read internetormedia;
else
	internetormedia=internet
fi

if [ "$internetormedia" == "internet" ];
then

	cd $PREFIX
	$WGET $PKGHOST/file-base.tar.bz2 -O$PREFIX/file-base.tar.bz2
	$TAR xf file-base.tar.bz2
	$RM file-base.tar.bz2

	if [ `$UNAME -m` == "x86_64" ]; then
		$LN -s lib lib64
		cd usr
		$LN -s lib lib64
	fi


	$CURL -L -s https://github.com/nemasu/noop-linux/raw/master/pkgr > $PREFIX/usr/sbin/pkgr

	$CHMOD a+x $PREFIX/usr/sbin/pkgr
	export PATH=$PREFIX/usr/sbin:$PATH

	PREFIX=$PREFIX pkgr -s
	export PKGR_SUPPRESS_P_OUTPUT=1

	if [ "`$UNAME -m`" == "x86_64" ];
	then
		EXTRA="grub cryptsetup dracut linux-kernel linux-firmware"
	fi

	for i in busybox glibc which bc tzdata systemd shadow coreutils bash wget grep sed perl findutils curl gawk procps tar bzip2 gzip dhcp dhcpcd inetutils iproute2 wpa_supplicant wireless_tools kbd vim run-parts ca-certificates openresolv networkmanager $EXTRA;
	do
		PREFIX=$PREFIX pkgr -i $i
	done
else

	if [ ! -d /var/noop/installed ]; then
	
		if [ "$LANG" == "ja_JP.UTF-8" ]; then
			echo "エラー：noopメディアから起動しませんでした。";
		else
			echo "Error: Not booted from valid noop Linux media, use internet instalation method.";
		fi
		exit 1;
	fi

	for i in `ls /var/noop/installed`
	do
		if [ "$LANG" == "ja_JP.UTF-8" ]; then
			echo "パッケージをコピーします　$i";
		else
			echo "Copying package $i"
		fi
		
		#Dirs
		for j in `sed -n -e '/FILES:/,$p' /var/noop/installed/$i | sed '/FILES:/d' | sed 's/^\(.*\/\).*/\1/g' | sort | uniq`;
		do
			if [ ! -d "$PREFIX/$j/" ]; then
				mkdir -p "$PREFIX/$j/"
			fi

		done
		
		#Files
		for j in `sed -n -e '/FILES:/,$p' /var/noop/installed/$i | sed '/FILES:/d'`;
		do  
			dest_dir=`echo $j |  sed -e 's/\(.*\/\).*/\1/g'`
			cp -pr "$j" "$PREFIX/$dest_dir/" 
		done
	done

	if [ "$LANG" == "ja_JP.UTF-8" ]; then
		echo -n "メタデータをコピーしています。。。";
	else
		echo -n "Copying metadata...";
	fi
	cp -r /var/noop $PREFIX/var/
	echo "done.";

	if [ "$LANG" == "ja_JP.UTF-8" ]; then
		echo -n "ベースファイルシステムをリセットしています。。。";
	else
		echo -n "Resetting base file system...";
	fi
	pushd $PREFIX &> /dev/null

	if [ -e /var/noop/file-base.tar.bz2 ]; then
		tar xf /var/noop/file-base.tar.bz2
	else
		wget nooplinux.org/noop/packages/x86_64/file-base.tar.bz2
		tar xf file-base.tar.bz2 && rm file-base.tar.bz2
	fi

	if [ `$UNAME -m` == "x86_64" ]; then
		$LN -s lib lib64
		cd usr
		$LN -s lib lib64
	fi
	popd &> /dev/null
	
	cp `which pkgr` $PREFIX/usr/sbin/pkgr
	export PATH=$PREFIX/usr/sbin:$PATH
	PREFIX=$PREFIX pkgr -s
	echo "done.";

fi

$MOUNT --bind /dev $PREFIX/dev
$MOUNT --bind /proc $PREFIX/proc
$MOUNT --bind /sys $PREFIX/sys
$CHROOT $PREFIX ldconfig
$CHROOT $PREFIX /bin/bash --login pkgr -init $2
