#!/bin/bash

#Current options: core, mate, xfce4, enlightenment
export NOOP_ISO_CREATE=$1

#Yes this is bad, but ISO creation is done in a VM anyways.
cd /root

if [ -e iso-fs ];
then
	umount iso-fs/dev iso-fs/sys iso-fs/proc;
fi
rm -rf iso iso-fs && mkdir -p iso iso-fs

#Initramfs
wget https://github.com/nemasu/noop-linux/raw/master/initramfs/mkinitramfs-live -Omkinitramfs 
chmod +x mkinitramfs 
./mkinitramfs

#Grab latest installer
wget https://github.com/nemasu/noop-linux/raw/master/instlr -Oinstlr
chmod +x instlr
./instlr  /root/iso-fs

umount iso-fs/dev iso-fs/sys iso-fs/proc;
cp -r /root/iso-fs/boot /root/iso
mv noop-initramfs-live.igz /root/iso/boot


wget https://github.com/nemasu/noop-linux/raw/master/etc/iso-grub.cfg -O/root/iso/boot/grub/grub.cfg
KERVER=`grep -m1 VER: /root/iso-fs/var/noop/installed/linux-kernel | sed -e 's/VER://g'`
sed -i -e 's/VERSION/'"$KERVER"'/' /root/iso/boot/grub/grub.cfg

mkdir -p /root/iso/EFI/boot/
cd /root/iso
grub-mkstandalone  --directory="/usr/lib/grub/x86_64-efi/" --format="x86_64-efi" --compress="xz" --output=EFI/boot/bootx64.efi boot/grub/grub.cfg
cd ..

if [ "$NOOP_ISO_CREATE" == "enlightenment" ];
then
	pushd /root/iso-fs/home/livecd
	wget http://www.nooplinux.org/dist/enlightenemnt-livecd-home.tar.xz
	tar xf enlightenemnt-livecd-home.tar.xz && rm enlightenemnt-livecd-home.tar.xz
	popd

fi

cd /root/iso-fs
mksquashfs * ../iso/root.sqsh
cd .. 


NAME_DATE=`date +%Y%m%d`
grub-mkrescue -o noop-${NOOP_ISO_CREATE}-${NAME_DATE}.iso iso
