function postinst() {
    gio-querymodules /usr/lib/gio/modules
    glib-compile-schemas /usr/share/glib-2.0/schemas
    killall -USR1 gvfsd >&/dev/null || :
}
function postup() {
    gio-querymodules /usr/lib/gio/modules
    glib-compile-schemas /usr/share/glib-2.0/schemas
    killall -USR1 gvfsd >&/dev/null || :
}
function postrm() {
    gio-querymodules /usr/lib/gio/modules
    glib-compile-schemas /usr/share/glib-2.0/schemas
}
