function postinst() {
    systemd-tmpfiles --create apache.conf
    getent group http &>/dev/null || groupadd -g 33 http >/dev/null
    getent passwd http &>/dev/null || useradd -u 33 -c "Apache Server" -g http -d /var/www -s /bin/false http >/dev/null
}
function postup() {
    systemd-tmpfiles --create apache.conf
}
function postrm() {
    getent passwd http &>/dev/null && userdel http >/dev/null
    getent group http &>/dev/null && groupdel http >/dev/null
}
