function postinst() {
    gtk-update-icon-cache -q -t -f /usr/share/icons/mate
    gtk-update-icon-cache -q -t -f /usr/share/icons/menta
}
function postup() {
    gtk-update-icon-cache -q -t -f /usr/share/icons/mate
    gtk-update-icon-cache -q -t -f /usr/share/icons/menta
}
function postrm() {
    gtk-update-icon-cache -q -t -f /usr/share/icons/mate
    gtk-update-icon-cache -q -t -f /usr/share/icons/menta
}
