function postinst() {
    chmod 644 /usr/share/fonts/OTF/*
    fc-cache -fs
    mkfontscale /usr/share/fonts/OTF
    mkfontdir /usr/share/fonts/OTF
}
function postup() {
    chmod 644 /usr/share/fonts/OTF/*
    fc-cache -fs
    mkfontscale /usr/share/fonts/OTF
    mkfontdir /usr/share/fonts/OTF
}
function postrm() {
    chmod 644 /usr/share/fonts/OTF/*
    fc-cache -fs
    mkfontscale /usr/share/fonts/OTF
    mkfontdir /usr/share/fonts/OTF
}
