function postinst() {
    glib-compile-schemas /usr/share/glib-2.0/schemas
    gtk-update-icon-cache -f -q -t /usr/share/icons/hicolor
}
function postup() {
    glib-compile-schemas /usr/share/glib-2.0/schemas
    gtk-update-icon-cache -f -q -t /usr/share/icons/hicolor
}
function postrm() {
    glib-compile-schemas /usr/share/glib-2.0/schemas
    gtk-update-icon-cache -f -q -t /usr/share/icons/hicolor
}
